package a4.transport.messenger;

/**
 * Event types generated by {@link Messenger}
 */
public enum EventType
{
    CONNECTION_RECEIVED,
    MESSAGE_SENT,
    MESSAGE_RECEIVED,
    INTERRUPT_RECEIVED
}
