package a4.transport.messenger;

/**
 * Event types generated by {@link Messenger}
 */
public enum EventType
{
    CONNECTION_RECEIVED,
    NOTIFICATION_SENT,
    NOTIFICATION_RECEIVED,
    REQUEST_RECEIVED,
    INTERRUPT_RECEIVED
}
